on:
  push:
    branches:
      - main

name: ssm ec2 instance

jobs:
  ssm:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: ssm connection
      run: aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "i-08396c85202039cb0" --parameters "commands=echo helloWorld" --cloud-watch-output-config "CloudWatchOutputEnabled=true,CloudWatchLogGroupName=ssmlog"
    
    
